# thanks to Renato66 for his Github Action

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
<<<<<<< Updated upstream
          reviewers: Spl4shh
          token: ${{ secrets.GITHUB_TOKEN }}
=======
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: Spl4shh # if draft, assigned when draft is released
>>>>>>> Stashed changes
