# thanks to Renato66 for his Github Action
name: Assign Reviewer
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: Spl4shh # if draft, assigned when draft is released
