# thanks to Renato66 for his Github Action

name: Managing New Issue
on:
  issues:
    types: ['opened', 'reopened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Labeling Issue
        uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{
            "Minor":["Minor"],
            "Medium":["Medium"],
            "Critical":["Critical"]
          }'
#          labels-not-allowed: '["good first issue"]'
          default-labels: '["toCheck"]'

      - name: Assigning Issue
        uses: pozil/auto-assign-issue@v1.4.0
        with:
            assignees: Spl4shh
            numOfAssignee: 1