# thanks to Renato66 for his Github Action

name: Running Test on Pull Request
on:
  pull_request:
    types: ['opened', 'ready_for_review']
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: Website/vendor/autoload.php
          configuration: Website/phpunit.xml.dist